### ISSUE TITLE
Lib doesn't compile on elixir-1.11.3-otp-23

### ISSUE THREAD

**Issue by collegeimprovements** [Qqwy/elixir-fun_land#35]
Elixir Version: 1.11.3-OTP-23
```
 › mix deps.compile fun_land                                                                                                              Desktop/deps_tracker
Found existing alias for "mix deps.compile". You should use: "mc"
==> fun_land
Compiling 27 files (.ex)

== Compilation error in file lib/fun_land/mappable.ex ==
** (CompileError) lib/fun_land/mappable.ex:30: type variable '_' is invalid
    (elixir 1.11.3) lib/kernel/typespec.ex:911: Kernel.Typespec.compile_error/2
    (elixir 1.11.3) lib/kernel/typespec.ex:311: Kernel.Typespec.translate_type/2
    (stdlib 3.14) lists.erl:1358: :lists.mapfoldl/3
    (elixir 1.11.3) lib/kernel/typespec.ex:235: Kernel.Typespec.translate_typespecs_for_module/2
    (elixir 1.11.3) src/elixir_erl_compiler.erl:12: anonymous fn/3 in :elixir_erl_compiler.spawn/2
```

**Comment by Qqwy** [comment]
Thank you for the heads-up!

**Comment by Qqwy** [comment]
Are you maybe still on an older version of `fun_land`? The line that the compiler is complaining about no longer has an underscore as type variable, and I am able to compile version `0.10.0` without any problems under Elixir 1.11.3-OTP-23.

**Comment by collegeimprovements** [comment]
Yes, I tried again. All works fine on a new project.
